const ADD_FILE_CONTENT = "ADD_FILE_CONTENT";
const REMOVE_FILE = "REMOVE_FILE";
const CLEAR_FILES = "CLEAR_FILES";
const SEND_EMAILS_START = "SEND_EMAILS_START";
const SEND_EMAILS_SUCCESS = "SEND_EMAILS_SUCCESS";
const SEND_EMAILS_ERROR = "SEND_EMAILS_ERROR";

export {
  ADD_FILE_CONTENT,
  REMOVE_FILE,
  CLEAR_FILES,
  SEND_EMAILS_START,
  SEND_EMAILS_SUCCESS,
  SEND_EMAILS_ERROR,
};
